version: "3.3"


  python:
    build: ./AppPython
    container_name: App_Python
    volumes: 
      - ./AppPython/:/AppPython
    ports:
      - "1235:1235"
    command: jupyter notebook --no-browser --ip=0.0.0.0 --port=1234 --allow-root
    depends_on:
      - mysql